build:
	gcc -Wall -o prod_cons_sem prod_cons_sem.c -lpthread
	gcc -Wall -o prod_cons_var_cond prod_cons_var_cond.c -lpthread
	gcc -Wall -o mutex mutex.c -lpthread
	gcc -Wall -o barrier barrier.c -lpthread
clean:
	rm prod_cons_sem prod_cons_var_cond mutex barrier