build:
	gcc helloworld.c -o helloworld -fopenmp
	gcc private_shared.c -o private_shared -fopenmp
	gcc for_loop.c -o for_loop -fopenmp
	gcc critical.c -o critical -fopenmp
clean:
	rm helloworld private_shared for_loop critical